#! /bin/sh

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $all
# Required-Stop:     $network $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server
# Description:       starts unicorn
### END INIT INFO

# Change these to match your app:
USER=cstep
APP_NAME=r2
APP_PATH=/home/cstep
ENV=$2
RBENV_RUBY_VERSION=2.2.1

# env
APP_ROOT="$APP_PATH/$APP_NAME"
SET_PATH="cd $APP_ROOT"
DAEMON="/home/cstep/r2/bin/bundle exec unicorn"
DAEMON_OPTS="-c $APP_ROOT/config/unicorn.rb -E $ENV -D"
CMD="$DAEMON $DAEMON_OPTS"
NAME=unicorn
DESC="Unicorn app for $APP_NAME"
PID="$APP_ROOT/tmp/pids/unicorn.pid"
OLD_PID="$PID.oldbin"

cd $APP_ROOT || exit 1

sig () {
        test -s "$PID" && kill -$1 `cat $PID`
}

oldsig () {
        test -s $OLD_PID && kill -$1 `cat $OLD_PID`
}

case ${1-help} in
start)
        sig 0 && echo >&2 "Already running" && exit 0
	#if [[ "$(id -u)" = "0" ]]; then
	#	echo "You must run this as cstep"
	#	exit 1
	#fi
	if [[ -z $2 ]]; then
		echo -e "You must enter an environment.\nExample: service unicorn start production"
		exit 1
	fi
	echo "Starting Server in $APP_ROOT"
	echo -e "\tCommand:\t$DAEMON $DAEMON_OPTS"
#        su - $USER -c "$CMD"
  $SET_PATH
  $CMD
        ;;
stop)
        sig QUIT && exit 0
        echo >&2 "Not running"
        ;;
force-stop)
        sig TERM && exit 0
        echo >&2 "Not running"
        ;;
restart|reload)
        sig HUP && echo reloaded OK && exit 0
        echo >&2 "Couldn't reload, starting '$CMD' instead"
        su - $USER -c "$CMD"
        ;;
upgrade)
        sig USR2 && exit 0
        echo >&2 "Couldn't upgrade, starting '$CMD' instead"
        su - $USER -c "$CMD"
        ;;
rotate)
        sig USR1 && echo rotated logs OK && exit 0
        echo >&2 "Couldn't rotate logs" && exit 1
        ;;
*)
        echo >&2 "Usage: $0 <start <environment>|stop|restart|upgrade|rotate|force-stop>"
        exit 1
        ;;
esac

exit 0
